// Build script for proposal-studio.
//
// Pipeline:
//   1. Read the editor HTML shell (public/custom-form/custom-form.html) and
//      inline every LOCAL css/js asset into a single self-contained HTML
//      document. CDN assets (jQuery, Froala, Font Awesome) stay as remote
//      <link>/<script> tags so we don't redistribute third-party code.
//   2. Emit that document as a JS module (a JSON-escaped string) so it can be
//      embedded straight into the bundle — the consumer needs zero static
//      assets, `npm install` just works.
//   3. Bundle src/index.js into ESM + CJS + IIFE(global) with esbuild.
//   4. Copy the hand-written type definitions into dist/.
//
// Run with Node 18+ (uses esbuild's JS API).  Node 22 recommended.
import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, '..');
// Source of truth for the editor engine = the existing pure-JS app.
const editorRoot = resolve(pkgRoot, '..', '..', 'public', 'custom-form');
const htmlEntry = join(editorRoot, 'custom-form.html');

const distDir = join(pkgRoot, 'dist');
const genDir = join(pkgRoot, 'src', '_generated');

// ---------------------------------------------------------------------------
// 1 + 2.  Inline local assets into one HTML document.
// ---------------------------------------------------------------------------

/** Read a local asset referenced by `./foo` relative to the editor root. */
function readLocal(href) {
  const clean = href.replace(/^\.\//, '').split(/[?#]/)[0];
  return readFileSync(join(editorRoot, clean), 'utf8');
}

function isLocal(href) {
  return href.startsWith('./') || href.startsWith('/custom-form/');
}

function inlineEditorHtml() {
  let html = readFileSync(htmlEntry, 'utf8');

  // Inline local stylesheets: <link rel="stylesheet" href="./...css">
  html = html.replace(
    /<link\b[^>]*?href=("|')([^"']+)\1[^>]*?>/gi,
    (tag, _q, href) => {
      if (!/stylesheet/i.test(tag) || !isLocal(href)) return tag; // keep CDN links
      const css = readLocal(href);
      return `<style data-src="${href}">\n${css}\n</style>`;
    }
  );

  // Inline local scripts: <script src="./...js"></script>
  html = html.replace(
    /<script\b[^>]*?src=("|')([^"']+)\1[^>]*?>\s*<\/script>/gi,
    (tag, _q, src) => {
      if (!isLocal(src)) return tag; // keep CDN scripts (jQuery / Froala)
      let js = readLocal(src);
      // A literal </script> inside inlined code would terminate the tag early.
      js = js.replace(/<\/script>/gi, '<\\/script>');
      return `<script data-src="${src}">\n${js}\n</script>`;
    }
  );

  // Let the host know when the engine has finished booting, and keep posting
  // height so auto-resize works even outside the original Angular host.
  const readySignal = `
<script data-injected="proposal-studio-ready">
(function () {
  function ping() {
    try {
      var canvas = document.querySelector('.custom-form-design');
      window.parent && window.parent.postMessage({
        source: 'proposal-studio',
        type: 'ready',
        ready: !!(canvas && window.FlowCanvas)
      }, '*');
      if (canvas && document.body) {
        window.parent && window.parent.postMessage({
          source: 'proposal-studio', type: 'iframe:height',
          height: document.body.scrollHeight
        }, '*');
      }
    } catch (e) {}
  }
  if (document.readyState === 'complete') ping();
  else window.addEventListener('load', ping);
  // Re-ping on DOM changes so the host can track height / readiness.
  new MutationObserver(function () { ping(); })
    .observe(document.documentElement, { childList: true, subtree: true });
})();
</script>`;

  html = html.replace(/<\/body>/i, `${readySignal}\n</body>`);
  return html;
}

console.log('[proposal-studio] inlining editor assets…');
const editorHtml = inlineEditorHtml();

mkdirSync(genDir, { recursive: true });
rmSync(distDir, { recursive: true, force: true });
mkdirSync(distDir, { recursive: true });

// Embed as a JS module — JSON.stringify gives a safe, fully-escaped literal.
writeFileSync(
  join(genDir, 'editor-html.js'),
  `// AUTO-GENERATED by scripts/build.mjs — do not edit.\n` +
    `export default ${JSON.stringify(editorHtml)};\n`
);
// Also drop a standalone copy for debugging / manual hosting.
writeFileSync(join(distDir, 'editor-document.html'), editorHtml);
console.log(`[proposal-studio] editor document: ${(editorHtml.length / 1024).toFixed(0)} KB`);

// ---------------------------------------------------------------------------
// 3.  Bundle the Web Component.
// ---------------------------------------------------------------------------
const entry = join(pkgRoot, 'src', 'index.js');
const shared = {
  entryPoints: [entry],
  bundle: true,
  target: ['es2019'],
  legalComments: 'none',
  logLevel: 'info'
};

await build({ ...shared, format: 'esm', outfile: join(distDir, 'proposal-studio.esm.js') });
await build({ ...shared, format: 'cjs', outfile: join(distDir, 'proposal-studio.cjs.js') });
await build({
  ...shared,
  format: 'iife',
  globalName: 'ProposalStudio',
  outfile: join(distDir, 'proposal-studio.global.js')
});
// Minified global for CDN <script> usage.
await build({
  ...shared,
  format: 'iife',
  globalName: 'ProposalStudio',
  minify: true,
  outfile: join(distDir, 'proposal-studio.global.min.js')
});

// ---------------------------------------------------------------------------
// 4.  Ship the type definitions.
// ---------------------------------------------------------------------------
const dts = readFileSync(join(pkgRoot, 'types', 'index.d.ts'), 'utf8');
writeFileSync(join(distDir, 'proposal-studio.d.ts'), dts);

console.log('[proposal-studio] build complete → dist/');
